### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by popouille** [matchory/response-cache#2]
Hello, i have this issue the the package:

`Exception
Serialization of 'Closure' is not allowed`

`vendor/matchory/response-cache/src/Repository.php:93`
`vendor/matchory/response-cache/src/ResponseCache.php:172`
`vendor/matchory/response-cache/src/Http/Middleware/CacheResponse.php:96`

**Comment by popouille** [comment]
solved, just add ->render() on view::make 

`return View::make()->render();`

**Comment by Radiergummi** [comment]
Might make sense to add a condition for that 🤔
